#pragma once

#include <winioctl.h>

#define DEFAULT_TXRX_BUFFFER_SIZE 4096

#define IOCTL_APPLINK_SET_BUFFER_SIZES	CTL_CODE(FILE_DEVICE_SERIAL_PORT,51,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_BUFFER_SIZES	CTL_CODE(FILE_DEVICE_SERIAL_PORT,52,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_READ_BUFFER		CTL_CODE(FILE_DEVICE_SERIAL_PORT,53,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_WRITE_BUFFER      CTL_CODE(FILE_DEVICE_SERIAL_PORT,54,METHOD_BUFFERED,FILE_ANY_ACCESS)

typedef struct {
	ULONG TransmitSize;
	ULONG ReceiveSize;
} BUFFER_SIZES;
