#pragma once

#include <minwindef.h>
#include <winioctl.h>

#define DEFAULT_TXRX_BUFFFER_SIZE 4096

#define IOCTL_APPLINK_SET_BUFFER_SIZES	CTL_CODE(FILE_DEVICE_SERIAL_PORT,51,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_BUFFER_SIZES	CTL_CODE(FILE_DEVICE_SERIAL_PORT,52,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_READ_BUFFER		CTL_CODE(FILE_DEVICE_SERIAL_PORT,53,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_WRITE_BUFFER      CTL_CODE(FILE_DEVICE_SERIAL_PORT,54,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_APPLINK_SET_COMSTATUS     CTL_CODE(FILE_DEVICE_SERIAL_PORT,55,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_APPLINK_GET_COMSTATUS		CTL_CODE(FILE_DEVICE_SERIAL_PORT,56,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_BAUD			CTL_CODE(FILE_DEVICE_SERIAL_PORT,57,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_TIMEOUTS		CTL_CODE(FILE_DEVICE_SERIAL_PORT,58,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_LINE_CONTROL	CTL_CODE(FILE_DEVICE_SERIAL_PORT,60,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_FLOW_CONTROL	CTL_CODE(FILE_DEVICE_SERIAL_PORT,61,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_APPLINK_GET_CHARS			CTL_CODE(FILE_DEVICE_SERIAL_PORT,62,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define IOCTL_APPLINK_WAIT_FOR_CHANGE	CTL_CODE(FILE_DEVICE_SERIAL_PORT,63,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define APPLINK_EVENT_COMSTATE	(ULONG) 0x01
#define APPLINK_EVENT_TIMEOUTS	(ULONG) 0x02
#define APPLINK_EVENT_CONFIG	(ULONG) 0x04
#define APPLINK_EVENT_NEWDATA	(ULONG) 0x08

typedef struct {
	ULONG TransmitSize;
	ULONG ReceiveSize;
} BUFFER_SIZES;
